### ISSUE TITLE
Monitoring stack fails on installation with stackablectl

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/demos#46]
Installing the monitoring stack with stackable fails when it reaches `prometheus-service-monitor.yaml`. Running the stack install a second time succeeds as does applying `prometheus-service-monitor.yaml` manually with `kubectl`. 
```
    manifests:
      - plainYaml: demos/stacks/monitoring/grafana-dashboards.yaml
      - helmChart: demos/stacks/_templates/prometheus.yaml
      - plainYaml: demos/stacks/_templates/prometheus-service-monitor.yaml
```
This could be a race condition between the installation of the Prometheus helm chart and the creation of the ServiceMonitors.
